version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5234:5234
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: belajar-nest
    networks:
      - psywar
networks:
  psywar:
